### ISSUE TITLE
Archive this repo

### ISSUE THREAD

**Issue by Himura2la** [tectonick/hackerembassy-tg-bot#10]
Чтобы избежать такого: https://github.com/hackerembassy/hackerembassy-tg-bot/pull/12, лучше наверно разорвать апстрим-форк отношения с репой https://github.com/hackerembassy/hackerembassy-tg-bot, заархивировать эту, и всё делать в бранчах. Я случайно два лишних PR создал в эту репу только что, потому что п дуфолту всё в апстрим льётся

**Comment by tectonick** [comment]
Будь осторожнее :) Но я что-нибудь сделаю

**Comment by tectonick** [comment]
Отправляю в архив
